# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6308a01cd55e2dca6fd9136476d8500ce76e17c6d8f54724d65f7260cad60f184fe0246d561308d880e42a784e4476cebf59c85e4d7f76df85793650dd866b73

test:
  secret_key_base: eac2108a5dded418ab34e6a20bf39bf1899904a2c4bfedd76ac0d06d229730d9f5393b9167a1945829b99d2c8195a62c321c8b026039c7c81f66f85c69309e43

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
